CREATE TABLE "Task" (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	ParentId INTEGER,
	CONSTRAINT Tasks_Tasks_FK FOREIGN KEY (ParentId) REFERENCES "Task"(Id)
);

CREATE TABLE WorkLog (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Title TEXT,
	Minutes INTEGER NOT NULL,
	TaskId INTEGER, Date TEXT,
	CONSTRAINT WorkLog_Tasks_FK FOREIGN KEY (TaskId) REFERENCES "Task"(Id)
);